### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [Navrin/hamiltonian-evo-simulator-uts41173#1]
I recently came across your project hamiltonian-evo-simulator-uts41173 and I noticed that the repository github.com/Navrin/hamiltonian-evo-simulator-uts41173 currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by Navrin** [comment]
Sure, I can add a license to this. I think I originally didn't include an open source license because it was for an assignment for my UTS class, but enough time has passed where it shouldn't matter anymore.

**Comment by Navrin** [comment]
Implemented in https://github.com/Navrin/hamiltonian-evo-simulator-uts41173/commit/fc5b7d2eea6980bc530f055d06387809a99a4034

**Comment by cbjuan** [comment]
Thanks!
